/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.dlopez.gradle101.app;

public class App {

    public static void main(String[] args) {
        new net.dlopez.gradle101.common.Hello().SayHello();
        System.out.println("Hello");
    }
}
